# Generated by Django 5.2.1 on 2025-05-26 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_is_sticky'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, help_text='Path or URL to avatar image', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('signature', models.TextField(blank=True)),
                ('user_title', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('timezone', models.CharField(choices=[('UTC', 'UTC'), ('US/Pacific', 'US/Pacific'), ('US/Eastern', 'US/Eastern'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Australia/Sydney', 'Australia/Sydney')], default='UTC', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('hidden', 'Hidden')], default='public', max_length=10)),
                ('notify_on_reply', models.BooleanField(default=True)),
                ('receive_newsletter', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
