# Generated by Django 5.2.1 on 2025-06-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_topic_category_alter_profile_avatar'),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tagging.tag'),
        ),
    ]
